### PR TITLE
Maven integration

### PR DESCRIPTION
**Pull request by mythsunwind**
Make integrating cryptobox-jni as dependency into other maven projects more seamless.
- Add pom.xml with version, groupId and artifactId
- Compile for java 7 to use it in older projects (for e.g. as jenkins plugin)
- Bundle native libraries into the jar file
- Load native libraries from jar if they cannot be loaded from java.library.path
- Package with classifier to get jar from repo for a specific platform/architecture

Example:

```
    <dependency>
      <groupId>com.wire.cryptobox</groupId>
      <artifactId>cryptobox-jni</artifactId>
      <version>0.8.2</version>
      <classifier>darwin-x86_64</classifier>
    </dependency>
```

### CODE REVIEW

**Comment by romanb** [comment]
Thanks for the proposal. It would definitely be nice to include "fat jars" in future releases that come bundled with the native artifacts, similar to the `.aar`s for Android, and can potentially be distributed in (public) maven repositories for ease of use. However, as it stands I see some problems with your current `NativeLibraryLoader`:

  * The code uses packages not available on Android (`java.nio.file`). We're even still using `-source` / `-target` `1.6` for the Android build.

  * It does not make sense to me that `System.loadLibrary` is tried first, i.e. that the native libraries bundled with the `.jar` have the lowest precedence. The current code would always fail with `"... could not find native library ... in jar"` if a library cannot be found, which can be highly misleading as it suggests that this is the only place being searched. I would at least expect it the other way around, i.e. to look for a bundled artefact first and if there is none then proceed with `System.loadLibrary` as usual. Even better would be no such fallback in either direction at runtime at all (see below for a suggestion).

I think both of these problems can be overcome by a form of conditional compilation: Having two versions of `NativeLibraryLoader`, a default implementation that only calls `System.loadLibrary` and another one that only looks for the libraries inside the jar. The latter is then only compiled into the "fat jar" builds, e.g. by overriding the file before compilation (or a different form of conditional compilation, if you know any). That way you don't need to unnecessarily constrain yourself to Android APIs in code paths that should never actually run on Android. Also, there is no need for a fallback in either direction at runtime between these different strategies for loading the native libraries since that choice is made at compile-time.

Is Maven (and thus a `pom.xml`) needed at all to build such a "fat jar"? I.e. what is maven-specific about the generated `.jar` file? Can you not install / distribute any ordinary `.jar` file in Maven repositories? It seems preferable to avoid the extra build-tool dependency and `pom.xml` just to build a jar that maven likes, if possible.

**Comment by mythsunwind** [comment]
Hi Roman,

thanks for the detailed review. I updated the source code to address to your valid points:

- Source is now completely Java 1.6 compatible (and errors are thrown if not)
- When I wrote the code I wanted to be as less invasive as possible, so the default behavior stayed the same. Now that I think about it, it makes not much sense to probe for libraries with `System.loadLibrary` when you actually expect a "fat jar". I solve it now with different profiles on compile time.
- Maven: I very much see the same issue with maven that you have. It seems to be never a good idea to use multiple build-tools and therefor add extra dependencies. Although in this case we actually build for two different worlds (rust, java). The use of two build-tools can be justified by this. I give you another argument: The main reason I see the use of maven justified here is to follow the idea of reliable and reproducible builds. Before you have told me, I was not aware that the jar should actually be built for Java 1.6. Maven gives you extra reliability now when it checks that this is done and also checks with the enforcer-plugin that new code is not introduced, which uses unsupported APIs. It also gives the ability to replace the version number in the JAR without my bad `sed` hack :)

**Comment by romanb** [comment]
> Source is now completely Java 1.6 compatible (and errors are thrown if not)

I still don't see how this can possibly build on Android. As I said earlier, the `java.nio.file` package is not available on Android, indeed it was only added in Java SE 7 ([link](https://docs.oracle.com/javase/7/docs/api/java/nio/file/package-summary.html)). So the enforcer plugin might not seem to do what you think it does. With Android the situation is not that easy anyway, i.e. the Android SDKs do not conform to the API of a specific JDK version. What parts of the JDK or even which features of newer Java versions are available on Android is a completely "arbitrary" subset chosen by Google, so trying to enforce a specific JDK or Java version to achieve Android compatibility is a futile effort. There is only one way to know if some code will build for Android, and that is to actually build it for Android.

> I solve it now with different profiles on compile time.

The result is still a choice made at runtime based on the presence of a `/fatjar` resource on the classpath. That might be acceptable if all of the code would actually built on Android (see above).

> Maven: [...]

I still don't understand why Maven is needed to build the desired "fat jar" file. Specifically, is it necessary that a jar file contains a `pom.xml` in order for the jar to be installed into a Maven repository? I don't mind if a minimal `pom.xml` is needed for building or inclusion in the jars, but I'd like to understand the reasoning behind it.

> I was not aware that the jar should actually be built for Java 1.6. Maven gives you extra reliability now when it checks that this is done and also checks with the enforcer-plugin that new code is not introduced, which uses unsupported APIs.

As I wrote above, the situation is not that simple w.r.t. what does and does not build on Android. It cannot be solved by just restricting yourself to a specific Java version, and the enforcer-plugin does not seem to do what you intended, unless I misinterpret your intention.

Unfortunately I feel like the recent changes have only made things more complicated (more maven plugins, use of profiles, ...) without achieving much. I would thus kindly ask you to revisit my earlier suggestion of having two completely distinct `NativeLibraryLoader` implementations and compile only one of them into a specific artifact, if possible without maven.

**Comment by romanb** [comment]
> I would thus kindly ask you to revisit my earlier suggestion of having two completely distinct NativeLibraryLoader implementations and compile only one of them into a specific artifact, if possible without maven.

Alternatively, as indicated before, a choice made at runtime based on the presence of a /fatjar resource on the classpath, as you are doing it right now, would also be good enough from my perspective **if** all of the code compiles on Android (API level 16+). See [here](https://developer.android.com/reference/packages.html) for what APIs are available.

**Comment by kim** [comment]
I have doubts that bundling `libcryptobox.so` is safe: not so much because of `glibc` (most people will probably trade that risk for the convenience), but because it seems to end up using fairly recent functions from `libgcc`:

```shell
$ objdump -T libcryptobox.so|grep GCC
0000000000000000      DF *UND* 	0000000000000000  GCC_3.3.1   __gcc_personality_v0
0000000000000000      DF *UND* 	0000000000000000  GCC_4.0.0   __powisf2
0000000000000000      DF *UND* 	0000000000000000  GCC_3.0     _Unwind_DeleteException
0000000000000000      DF *UND* 	0000000000000000  GCC_3.0     _Unwind_RaiseException
0000000000000000      DF *UND* 	0000000000000000  GCC_3.3     _Unwind_FindEnclosingFunction
0000000000000000      DF *UND* 	0000000000000000  GCC_3.3     _Unwind_Backtrace
0000000000000000      DF *UND* 	0000000000000000  GCC_4.0.0   __powidf2
0000000000000000      DF *UND* 	0000000000000000  GCC_4.2.0   _Unwind_GetIPInfo
0000000000000000      DF *UND* 	0000000000000000  GCC_3.0     _Unwind_Resume
```

Instead, I'd suggest to only bundle the native half of the JNI binding (`libcryptobox-jni.so`) and leave it to the user to install the rest through some other means ([cryptobox-c](http://github.com/wireapp/cryptobox-c) can be packaged into a .deb).

**Comment by mythsunwind** [comment]
Would it be possible to static link the libraries to eliminate the dependency of a certain glibc or libgcc version?

**Comment by kim** [comment]
@mythsunwind this would mean statically linking to the JVM itself, which I'm afraid isn't an option for most users. See http://openjdk.java.net/jeps/178

**Comment by romanb** [comment]
> I have doubts that bundling libcryptobox.so is safe [...]

That is a good point when it comes to the distribution of such binaries with releases (which we've mostly only done for OSX so far). I still think simply offering a "fat jar" packaging as an alternative to the already existing tarball packaging can be a useful addition, assuming you still build these archives yourself on the same or compatible host system to which you want to deploy the resulting binaries, i.e. it only provides more options on how you can distribute / deploy the dependencies resulting from your own builds.

> Instead, I'd suggest to only bundle the native half of the JNI binding (libcryptobox-jni.so) and leave it to the user to install the rest through some other means (cryptobox-c can be packaged into a .deb).

I agree that we're currently missing build artifacts (tarballs / jarballs) that only contain the libcryptobox-jni native library. After all, it is an intrinsic part of this project whereas the others are mere dependencies. It would also be the only native library included in a debian package for this project, if we were to create one in the future. For this PR that would mean each native library needs to be checked for it's presence in the jar individually, going through `System.loadLibrary` if it's not present, instead of just checking for the presence of `/lib`.

Getting back to the distribution of binaries with releases in general, how about we simply explain the risks of using the pre-built binaries (specifically of the dependencies) and mention the host system(s) they were built on (e.g. similar to how it is done for [GHC releases](https://www.haskell.org/ghc/download_ghc_8_0_1#linux_x86_64), possibly including the output of `objdump` (resp. `otool` for OSX) of each of the three native libraries in the release notes? It's a bit more more work but I think the pre-built binaries have proven to be useful so far, specifically for development purposes, and there specifically for OSX (they were added due to demand, after all).

**Comment by kim** [comment]
If you're willing to provide distro-specific binary packages, I would suggest considering travis-ci. They do provide several versions of OS X, yet don't have a big choice of Linux distros. However, [docker builds](https://docs.travis-ci.com/user/docker/) could be used to build on various distros relatively painlessly.

However, including a distro identifier (like GHC) would require users to specify it manually (`os.name` and `os.arch` are available as variables in a pom file). This can be confusing, especially when `cryptobox-jni` is a transitive dependency. But probably there is just no better way.

**Pull request closed without merging**
