### PR TITLE
Build cryptobox-jni for Windows 64-bit

### PR DESCRIPTION
**Pull request by mythsunwind**

### CODE REVIEW

**Comment by romanb** [comment]
Thanks. A few comments and suggestions:

  1. The special-handling of the `lib` prefix seems too complicated and inconsistent for my taste. If I understand the problem correctly, then the libsodium binary will always be called `libsodium.dll` and since `System.loadLibrary` does not add a `lib` prefix on Windows, it needs to be invoked with the name `"libsodium"` on Windows. Ok, but then I'd rather do this consistently on Windows for all the produced binaries, i.e. I'd rather see the `LIB_PREFIX` removed from the build so that we also have the names `libcryptobox.dll` and `libcryptobox-jni.dll` on Windows and just add the `lib` prefix to all `System.loadLibrary` calls on Windows.
  
  2. Which versions of Windows are actually supported? Can that be narrowed down?

  3. Is the OS-specific Java include directory for header files always called `win32` on Windows, no matter the architecture?

**Comment by mythsunwind** [comment]
1. The special handling of the `lib`-prefix on Windows was a very unpleasant experience for me. My personal conclusion was that libsodium.dll should be actually called sodium.dll on Windows, but that needs to be changed upstream. Your suggestion seems to be reasonable, although I struggle to find the right files and parameters to change cryptobox-jni and cryptobox to contain the prefix. Maybe you can help me there.

2. I have build it on Windows 7 (Home Premium). On Monday I can try to find out if the binaries that I created are compatible with Windows 8 and 10, but I assume that it's upwards compatible.

3. The OS-specific Java include directory for the header is always called `win32` on Windows, even when having the Windows x64 Java SE Development Kit installed on a Windows 64-bit.

**Comment by romanb** [comment]
> The special handling of the lib-prefix on Windows was a very unpleasant experience for me. My personal conclusion was that libsodium.dll should be actually called sodium.dll on Windows, but that needs to be changed upstream. Your suggestion seems to be reasonable, although I struggle to find the right files and parameters to change cryptobox-jni and cryptobox to contain the prefix. Maybe you can help me there.

Ok, I think I see what you mean and the alternative might not be as simple as I thought. I will need to think about it some more and will get back to you.

**Comment by mythsunwind** [comment]
I could successfully verify that the DLLs that I built on Windows 7 also work on Windows 10. Messages could be encrypted using the same DLLs and the libraries are fully in use on our test automation of the Windows Wrapper for some days now.

Any news on the way we want to deal with the prefixes?

**Comment by romanb** [comment]
Thanks, I will probably merge it today or tomorrow with some cosmetic changes.

**Pull request merged**
